### ISSUE TITLE
AOE Miner wipes NBT when breaking blocks

### ISSUE THREAD

**Issue by NielsPilgaard** [Mowmaster/Ensorcelled#2]
Original report: https://github.com/NillerMedDild/Enigmatica6/issues/1179

The contents of Storage Drawers are voided when broken from the range of AOE miner. Usually, when the drawers are broken they drop with their content inside them.

### Versions
- Ensorcelled 0.1a
- Forge-1.16.5-36.0.10

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Ensorcelled/commit/00836154af478efa22f44834d30725b3d2eb68d8
